import { Tray, Menu, nativeImage, app } from 'electron'
import { join } from 'node:path'
import { t } from './i18n'

let tray: Tray | null = null
let onTestFlight: (() => void) | null = null
let onSettings: (() => void) | null = null

function buildMenu(): Menu {
  return Menu.buildFromTemplate([
    { label: t('tray.open'), click: () => onSettings?.() },
    { label: t('tray.testFlight'), click: () => onTestFlight?.() },
    { type: 'separator' },
    { label: t('tray.quit'), click: () => app.quit() }
  ])
}

/** Creates the menu-bar / system-tray icon and its menu. */
export function createTray(testFlightCb: () => void, settingsCb: () => void): Tray {
  onTestFlight = testFlightCb
  onSettings = settingsCb
  // The icons are generated by scripts/generate-tray-icon.cjs into build/ (dev)
  // and shipped via extraResources into Resources/ (packaged app).
  // createFromPath automatically picks up the @2x variant when present.
  const iconPath = app.isPackaged
    ? join(process.resourcesPath, 'iconTemplate.png')
    : join(app.getAppPath(), 'build', 'iconTemplate.png')
  let image = nativeImage.createFromPath(iconPath)
  if (image.isEmpty()) {
    image = nativeImage.createEmpty()
  }
  // Template image = macOS auto-adapts it to light/dark menu bars.
  if (process.platform === 'darwin') {
    image.setTemplateImage(true)
  }

  tray = new Tray(image)
  tray.setToolTip(t('tray.tooltip'))
  tray.setContextMenu(buildMenu())
  return tray
}

/** Re-applies localized labels after a language change (icon is kept). */
export function rebuildTray(): void {
  if (!tray) return
  tray.setToolTip(t('tray.tooltip'))
  tray.setContextMenu(buildMenu())
}
